#!/usr/bin/env python3
"""Log terminite's working sessions.

Reads the Claude Code session transcripts for this project and writes a clean,
readable conversation log — human turns and AI turns, the tool noise stripped —
into `conversations/`.

This archives the raw record. The *story*, with a voice, lives in
`guide/history.md` — the AI partner's blog, written by hand. A script can keep a
transcript; it cannot write the blog.

Usage:
    python3 tools/log_session.py
"""

from __future__ import annotations

import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_DIR = REPO_ROOT / "conversations"
# Claude Code keeps one .jsonl transcript per session, in a directory named
# after the project path with every "/" turned into "-".
TRANSCRIPTS = Path.home() / ".claude" / "projects" / str(REPO_ROOT).replace("/", "-")

# Harness-injected text that is not part of what a human actually said.
NOISE = [
    re.compile(r"<system-reminder>.*?</system-reminder>", re.DOTALL),
    re.compile(r"<command-[^>]*>.*?</command-[^>]*>", re.DOTALL),
    re.compile(r"<local-command-[^>]*>.*?</local-command-[^>]*>", re.DOTALL),
]


def text_blocks(message: dict) -> str:
    """Join the plain-text content of a message; ignore tool calls and results."""
    content = message.get("content")
    if isinstance(content, str):
        return content
    if isinstance(content, list):
        return "\n".join(
            block.get("text", "")
            for block in content
            if isinstance(block, dict) and block.get("type") == "text"
        )
    return ""


def human_said(message: dict) -> str:
    """The words a human actually typed — harness noise stripped out."""
    text = text_blocks(message)
    for pattern in NOISE:
        text = pattern.sub("", text)
    return text.strip()


def conversation(rows: list[dict]) -> list[tuple[str, str]]:
    """Fold a transcript into an alternating list of (speaker, text) turns."""
    turns: list[tuple[str, str]] = []
    pending: list[str] = []  # AI text accumulating until the next human turn

    def flush_ai() -> None:
        if pending:
            turns.append(("Claude", "\n\n".join(pending)))
            pending.clear()

    for row in rows:
        if row.get("type") not in ("user", "assistant"):
            continue
        if row.get("isSidechain") or row.get("isMeta"):
            continue
        message = row.get("message")
        if not isinstance(message, dict):
            continue

        if row.get("type") == "assistant":
            said = text_blocks(message).strip()
            if said:
                pending.append(said)
        else:
            said = human_said(message)
            if not said:  # a tool result or pure harness noise — not conversation
                continue
            flush_ai()
            turns.append(("Human", said))

    flush_ai()
    return turns


def render(rows: list[dict], session_id: str) -> str:
    turns = conversation(rows)
    stamps = [r["timestamp"] for r in rows if r.get("timestamp")]
    date = stamps[0][:10] if stamps else "unknown"
    humans = sum(1 for who, _ in turns if who == "Human")
    replies = len(turns) - humans

    out = [
        f"# Session — {date}",
        "",
        f"_terminite working session `{session_id[:8]}` — "
        f"{humans} human turns, {replies} replies._  ",
        "_The raw record, generated by `tools/log_session.py`. "
        "The story — with a voice — is in [`guide/history.md`](../guide/history.md)._",
        "",
        "---",
    ]
    for who, said in turns:
        out += ["", f"### {who}", "", said]
    out.append("")
    return "\n".join(out)


def main() -> int:
    if not TRANSCRIPTS.is_dir():
        print(f"no transcripts directory: {TRANSCRIPTS}", file=sys.stderr)
        return 1

    transcripts = sorted(TRANSCRIPTS.glob("*.jsonl"))
    if not transcripts:
        print(f"no .jsonl transcripts in {TRANSCRIPTS}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(exist_ok=True)
    for path in transcripts:
        rows: list[dict] = []
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                rows.append(json.loads(line))
            except json.JSONDecodeError:
                continue  # skip a partial line rather than fail the whole run
        if not rows:
            continue
        session_id = rows[0].get("sessionId") or path.stem
        date = next((r["timestamp"][:10] for r in rows if r.get("timestamp")), "unknown")
        out_path = OUT_DIR / f"{date}-{session_id[:8]}.md"
        out_path.write_text(render(rows, session_id))
        print(f"logged  {out_path.relative_to(REPO_ROOT)}  ({len(rows)} transcript lines)")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
